-- 1. Wipe all existing tables and their dependencies
DROP TABLE IF EXISTS PlayerStats CASCADE;
DROP TABLE IF EXISTS OffensiveStats CASCADE;
DROP TABLE IF EXISTS DefensiveStats CASCADE;
DROP TABLE IF EXISTS Player CASCADE;
DROP TABLE IF EXISTS Games CASCADE;
DROP TABLE IF EXISTS Teams CASCADE;
DROP TABLE IF EXISTS Seasons CASCADE;
DROP TABLE IF EXISTS Stadiums CASCADE;
DROP TABLE IF EXISTS snapcounts CASCADE;
DROP TABLE IF EXISTS specialteamstats CASCADE;
DROP TABLE IF EXISTS weather CASCADE;
DROP TABLE IF EXISTS Trade_Failure_Log CASCADE;
DROP TABLE IF EXISTS conference CASCADE;
DROP TABLE IF EXISTS division CASCADE;

DROP TABLE IF EXISTS games_staging CASCADE;
DROP TABLE IF EXISTS temp_off_stats_staging CASCADE;
DROP TABLE IF EXISTS temp_nflverse_players CASCADE;
DROP TABLE IF EXISTS snapcounts_staging CASCADE;
-- 2. Wipe existing procedures and functions
--DROP FUNCTION IF EXISTS GetPlayerStats(INT) CASCADE;
--DROP FUNCTION IF EXISTS GetPlayerStatsByName(TEXT, TEXT, TEXT) CASCADE;
--DROP FUNCTION IF EXISTS GetPlayerLatestStats(TEXT, TEXT, TEXT) CASCADE;
--DROP PROCEDURE IF EXISTS UpdatePlayerTeamByName(TEXT, TEXT, TEXT, TEXT) CASCADE;
--DROP PROCEDURE IF EXISTS RetirePlayerByName(TEXT, TEXT, TEXT) CASCADE;